# Generated by Django 5.0.3 on 2024-03-12 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gotvac",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=60)),
                ("bio", models.EmailField(max_length=254)),
                ("profile_picture", models.ImageField(upload_to="")),
                ("date_of_birth", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Pregled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating_cook",
                    models.CharField(
                        choices=[
                            ("ED", "1"),
                            ("DV", "2"),
                            ("TR", "3"),
                            ("CT", "4"),
                            ("PT", "5"),
                        ],
                        max_length=3,
                    ),
                ),
                ("komentar", models.CharField(max_length=90)),
                ("datum_dodavanje", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="SlikaRecept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slika", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="KnigaZaGotvenje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naslov", models.CharField(max_length=90)),
                (
                    "tip_kujna",
                    models.CharField(
                        choices=[
                            ("IT", "italjanska"),
                            ("CH", "kineska"),
                            ("JP", "japonska"),
                            ("MX", "meksikanska"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "gotvac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.gotvac"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naslov", models.CharField(max_length=50)),
                (
                    "kategorija",
                    models.CharField(
                        choices=[
                            ("IT", "italjanska"),
                            ("CH", "kineska"),
                            ("JP", "japonska"),
                            ("MX", "meksikanska"),
                        ],
                        max_length=3,
                    ),
                ),
                ("opis", models.CharField(max_length=60)),
                ("sostojki", models.CharField(max_length=90)),
                ("instrukcii", models.CharField(max_length=90)),
                ("dali_veganski", models.BooleanField()),
                ("dali_bez_gluten", models.BooleanField()),
                (
                    "gotvac",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.gotvac"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NagradaRecept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naslov_nagrada", models.CharField(max_length=90)),
                ("datum_dobiena_nagrada", models.DateField()),
                (
                    "recept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.recept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KnigaRecepti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kniga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labapp.knigazagotvenje",
                    ),
                ),
                (
                    "recept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.recept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceptPregled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pregled",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.pregled"
                    ),
                ),
                (
                    "recept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.recept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceptSliki",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="labapp.recept"
                    ),
                ),
                (
                    "slika",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labapp.slikarecept",
                    ),
                ),
            ],
        ),
    ]
