# Generated by Django 5.0.3 on 2024-03-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategorija",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ime_kategorija", models.CharField(max_length=50)),
                ("opis", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="gotvac",
            name="kategorija",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="labapp.kategorija",
            ),
        ),
    ]
